export const FETCH_RECIPES = 'FETCH_RECIPES'; //FETCH
export const FETCH_COLEC = 'FETCH_COLEC'; //FETCH

export const RECEITA_CARRINHO = 'RECEITA_CARRINHO'; //LOCAL
export const CARRINHO_ADD = 'CARRINHO'; //LOCAL


export const COLECCAO_DELETE = 'COLECCAO_DELETE'; //DELETE
export const RECEITA_DELETE = 'RECEITA_DELETE'; //DELETE
export const CARRINHO_DELETE = 'CARRINHO_DELETE'; //DELETE


export const RECEITA_ADD = 'RECEITA_ADD'; //POST
export const COLECCAO_CREATE= "COLECCAO_CREATE"; //POST



